### ISSUE TITLE
is this still being maintained?

### ISSUE THREAD

**Issue by ahl** [slackapi/slack-api-specs#21]
### Description

Is this repo still being maintained? It doesn't seem to include all published endpoints. For example, it's missing `chat.scheduleMessage`

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-api-specs/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by episod** [comment]
We finally made an update! `chat.scheduleMessage` is now part of the method corpus on master, and should include all but a very select few published endpoints.
