### ISSUE TITLE
Implementing `views.*` methods?

### ISSUE THREAD

**Issue by agius** [slackapi/slack-api-specs#29]
### Description

Hello Slack folks!

I was trying to implement the [new modal views](https://api.slack.com/block-kit/surfaces/modals) in one of my apps, but the [views.open](https://api.slack.com/methods/views.open), [views.push](https://api.slack.com/methods/views.push), and [views.update](https://api.slack.com/methods/views.update) methods are not available in [slack-ruby/slack-ruby-client](https://github.com/slack-ruby/slack-ruby-client) . After reading the source for that library, it looks like the methods are missing because they are not in [the OpenAPI spec](https://api.slack.com/specs/openapi/v2/slack_web.json).

Is support for these new methods coming? Is there a timeline for implementation? I'm wondering if I should abandon `slack-ruby-client` and just write my own instead.

Thanks!

### What type of issue is this? (place an `x` in one of the `[ ]`)

- [ ] bug
- [X] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [X] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-api-specs/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by episod** [comment]
I hope to get a new OpenAPI spec generated in time for our Spec conference next week -- it's a pretty manual process unfortunately. I'll update this ticket when it goes out -- it'll include the views.* methods. 

I'm not sure if the slack-ruby-client uses the OpenAPI spec to build its definition or not, but in the meantime you can _should_ be able to use the library's more abstract web request interface to start interacting with the method directly, without a bit of the abstraction.

```ruby
response = Slack::Web::Faraday::Request::post("https://slack.com/api/views.open", your_method_arguments)
```

**Comment by agius** [comment]
@episod Thanks for the quick and helpful response! That solves my issue for now.

Looks like I was wrong, slack-ruby actually uses [slack-api-ref](https://github.com/slack-ruby/slack-api-ref), which scrapes the web documentation. Doesn't look like there is movement to switch it over to slack-api-spec, since [this issue has been open](https://github.com/slack-ruby/slack-ruby-client/issues/204) since April 2018 😿 

Good luck with the Spec conference!

**Comment by idyll** [comment]
@episod did you ever get the OpenAPI spec updated?

I'm maintaining an autogenerated package for Elixir and it looks like we're still missing the `views.*` details in the OpenAPI spec.

I'd prefer it if I didn't need to manually write in support for the views...

**Comment by acconrad** [comment]
@idyll any chance you have that available somewhere? would love to get this added to the Elixir-Slack package, we're experiencing the same problem there as well: https://github.com/BlakeWilliams/Elixir-Slack/issues/150

**Comment by episod** [comment]
Good news, `views.*` is now in the spec. Let us know if you have any issues with them.
