### ISSUE TITLE
Mark Repo as Unmaintained

### ISSUE THREAD

**Issue by platinummonkey** [slackapi/slack-api-specs#65]
### Description
Following this comment - don’t waste people’s time or efforts. It the project is unmaintained and the product is proprietary. Clearly the “incredible machine” is broken as well. 

https://github.com/slackapi/slack-api-specs/pull/55#issuecomment-912830958

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [ ] question
- [x] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-api-specs/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by filmaj** [comment]
I have issued #64 in an attempt to address this, btw
